import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Instrument_Serif,
  Urbanist,
  VT323,
} from "next/font/google";
import "./globals.css";
import { ThemeProviders } from "@/components/common/ThemeProviders";
import PageTransitionWrapper from "@/components/common/PageTransitionWrapper";
import Layout from "@/components/common/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Instrument_Serif({
  variable: "--font-geist-mono",
  weight: ["400"],
  subsets: ["latin"],
});

const vt323 = VT323({
  variable: "--font-digital",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sakthivel | Frontend developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${vt323.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body>
        <ThemeProviders>
          <PageTransitionWrapper>
            <Layout>{children}</Layout>
          </PageTransitionWrapper>
        </ThemeProviders>
      </body>
    </html>
  );
}
