import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Serif, Urbanist } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/common/Providers";
import PageTransitionWrapper from "@/components/common/PageTransitionWrapper";
import Layout from "@/components/common/Layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Instrument_Serif({
  variable: "--font-geist-mono",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sakthivel | Frontend developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <PageTransitionWrapper>
            <Layout>{children}</Layout>
          </PageTransitionWrapper>
        </Providers>
      </body>
    </html>
  );
}
